### ISSUE TITLE
Getting compile time error in HTML.java

### ISSUE THREAD

**Issue by gurungmukund** [mwilliamson/java-mammoth#21] opened 2020-08-10 12:21 UTC
After downloading the code, when I am trying to compile the code using maven there are below compile time errors in HTML.java

The method getChildren() is undefined for the type Object	line 144	

The method getChildren() is undefined for the type Object	line 147	

The method isMatch(HtmlElement, HtmlElement) in the type Html is not applicable for the arguments (Object, HtmlElement)	line 141	

Type mismatch: cannot convert from Optional<HtmlElement> to Optional<Object>	line 138

**Comment by mwilliamson** [comment] 2020-08-15 14:30
I'm not sure where you're seeing these errors -- there isn't a file called `HTML.java` in the codebase.

**Comment by gurungmukund** [comment] 2020-08-17 07:36
![Capture](https://user-images.githubusercontent.com/47946197/90370121-7a49ff80-e08a-11ea-8d43-ef77c1a1cec1.JPG)

**Comment by mwilliamson** [comment] 2020-09-02 14:06
What environment are you using? For instance, what compiler/JDK and operating system are you using?

**Comment by gurungmukund** [comment] 2020-09-03 06:23
JDK 1.8.0_121 and OS is Windows 10

**Comment by mwilliamson** [comment] 2024-02-18 13:11
I'm closing this since I can't reproduce it, and presumably most users are just downloading the jar. If someone has reproduction steps, then feel free to open another issue.

**Closed by mwilliamson** 2024-02-18 13:11 UTC
Labels: need more info
