### ISSUE TITLE
Missing Tab when use docxToHtml to convert docx

### ISSUE THREAD

**Issue by gowelaine** [mwilliamson/java-mammoth#29] opened 2022-02-02 11:06 UTC
Hi, I tried different documents has w:tab in docx's document.xml, however, the result does not contain any \t for w:tab

See docx below, when I turn on the indicate mode, you can clearly see that there is tab indicate "->" as shown below

![image](https://user-images.githubusercontent.com/92551051/152141743-184ab088-f506-4a41-8efe-d8d95015d656.png)

Test Document: 

[Test_Tab.docx](https://github.com/mwilliamson/java-mammoth/files/7985819/Test_Tab.docx)

I'm using kotlin as the language

Expected:
 this.hideloader();
                                                        Love is pain
                                                        Testing Tab
Try to figure out               what is this
Try to figure out                     what is this

With Html

`<p>this.hideloader();</p>`
`<p> \t \t \t \t \t Love is Pain</p>`
`<p> \t \t \t \t \t Testing Tab </p>`
`<p>Try to figure out \t what is this</p>`
`<p>Try to figure out \t \t what is this</p>`

but get this below in html string

`<p>this.hideloader();</p>`
`<p> Love is Pain</p>`
`<p> Testing Tab </p>`
`<p>Try to figure out what is this</p>`
`<p>Try to figure out what is this</p>`

**Comment by mwilliamson** [comment] 2022-02-02 20:39
It looks to me as though the tabs are correctly being converted to tab characters in the output. However, most of the time in HTML, whitespace will be collapsed to a single space. You'll need to use a `pre` or CSS to preserve whitespace.

**Comment by gowelaine** [comment] 2022-02-02 21:29
Hi, thank you for you response, you mean you can see this in your html string output?:

<p>this.hideloader();</p>
<p> \t \t \t \t \t Love is Pain</p>
<p> \t \t \t \t \t Testing Tab </p>
<p>Try to figure out \t what is this</p>
<p>Try to figure out \t \t what is this</p>

I can only see:
<p>this.hideloader();</p>
<p> Love is Pain</p>
<p> Testing Tab </p>
<p>Try to figure out what is this</p>
<p>Try to figure out what is this</p>

My output does not contain any \t.

**Comment by mwilliamson** [comment] 2022-02-02 22:53
How are you viewing that output? Just printing it to stdout? My (perhaps incorrect) recollection is that Mammoth doesn't put any newlines in.

**Comment by gowelaine** [comment] 2022-02-03 00:21
Sorry for the confusion, I list in that way so they can be view better in github. Yes, I did console.log() on UI side.
This is my extracted html string looks like:

<p>this.hideloader();</p> <p> Love is Pain</p> <p> Testing Tab </p> <p>Try to figure out what is this</p> <p>Try to figure out what is this</p>

**Comment by gowelaine** [comment] 2022-02-03 01:02
Oh Actually, after I added the <pre></pre> in UI, the tabs are showing now. Thank you very much!

**Comment by mwilliamson** [comment] 2022-02-03 09:06
Your best bet is probably to run a post-transformation step i.e. use an HTML processing library to find any tabs and convert them to whatever you want.

Closing since Mammoth is working as intended.

**Closed by mwilliamson** 2022-02-03 09:06 UTC
